version: "3.9"
services:
  rails:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/kimchi
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    command: mongod