version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kimchi
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    command: mongod --config /usr/local/etc/mongod.conf 2>&1 > /dev/null